<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="modbus_tcp" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-01-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Outputs" Type="CLIENT_1" x="2300" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_01"/>
		</FB>
		<FB Name="SPLIT_BYTE_INTO_BOOLS" Type="SPLIT_BYTE_INTO_BOOLS" x="3900" y="1400">
		</FB>
		<FB Name="ASSEMBLE_BYTE_FROM_BOOLS" Type="ASSEMBLE_BYTE_FROM_BOOLS" x="-1200" y="1400">
			<Parameter Name="BIT_00" Value="TRUE"/>
			<Parameter Name="BIT_05" Value="TRUE"/>
		</FB>
		<FB Name="SPLIT_BYTE_INTO_BOOLS_1" Type="SPLIT_BYTE_INTO_BOOLS" x="3900" y="2800">
		</FB>
		<FB Name="Inputs" Type="CLIENT_0_1" x="2300" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_02"/>
		</FB>
		<FB Name="F_BYTE_TO_WORD" Type="F_BYTE_TO_WORD" x="500" y="1400">
		</FB>
		<EventConnections>
			<Connection Source="Outputs.CNF" Destination="SPLIT_BYTE_INTO_BOOLS.REQ"/>
			<Connection Source="Inputs.CNF" Destination="SPLIT_BYTE_INTO_BOOLS_1.REQ"/>
			<Connection Source="ASSEMBLE_BYTE_FROM_BOOLS.CNF" Destination="F_BYTE_TO_WORD.REQ"/>
			<Connection Source="F_BYTE_TO_WORD.CNF" Destination="Outputs.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Outputs.RD_1" Destination="SPLIT_BYTE_INTO_BOOLS.IN" dx1="420"/>
			<Connection Source="Inputs.RD_1" Destination="SPLIT_BYTE_INTO_BOOLS_1.IN" dx1="406.67"/>
			<Connection Source="ASSEMBLE_BYTE_FROM_BOOLS." Destination="F_BYTE_TO_WORD.IN"/>
			<Connection Source="F_BYTE_TO_WORD.OUT" Destination="Outputs.SD_1" dx1="433.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
