<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DI" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_8_DO" Type="logiBUS_8_DO" x="-3300" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DigitalOutput_Q1" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q1'"/>
			<Parameter Name="DigitalOutput_Q2" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q2'"/>
			<Parameter Name="DigitalOutput_Q3" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q3'"/>
			<Parameter Name="DigitalOutput_Q4" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q4'"/>
			<Parameter Name="DigitalOutput_Q5" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q5'"/>
			<Parameter Name="DigitalOutput_Q6" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q6'"/>
			<Parameter Name="DigitalOutput_Q7" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q7'"/>
			<Parameter Name="DigitalOutput_Q8" Value="'App.Control.func.modbus_tcp.Inputs.DigitalOutput_Q8'"/>
		</FB>
		<FB Name="logiBUS_8_DI" Type="logiBUS_8_DI" x="-3333.33" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DigitalInput_I1" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I1'"/>
			<Parameter Name="DigitalInput_I2" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I2'"/>
			<Parameter Name="DigitalInput_I3" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I3'"/>
			<Parameter Name="DigitalInput_I4" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I4'"/>
			<Parameter Name="DigitalInput_I5" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I5'"/>
			<Parameter Name="DigitalInput_I6" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I6'"/>
			<Parameter Name="DigitalInput_I7" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I7'"/>
			<Parameter Name="DigitalInput_I8" Value="'App.Control.func.modbus_tcp.Outputs.DigitalInput_I8'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
